### ISSUE TITLE
Red and blue colors inverted when outputting a texture

### ISSUE THREAD

**Issue by YohannLYD** [hanasaan/ofxDeckLink#1]
Hello,

When I output a texture/FBO, the colors are correct in the window on Mac OS but the red and the blue colors are inverted on the SDI output/monitor (I made the verification with a color bars pattern).

I haven't found the way to change the pixel format (BMDPixelFormat?) in the ofxDeckLinkOutput class.
Is there a setting to change on my output object so the Decklink outputs the colors in the right order?

Here is my system in case this helps :
- MacPro4,1 + Mac OS 10.9.5
- DeckLink Studio 4K
- Blackmagic Desktop Video 10.5.4

Thanks

**Comment by hanasaan** [comment]
Sorry for really late reply.
I've fixed the issue.
